package com.surprising.instrument.api.model;

import java.time.Instant;
import java.util.List;

public record InstrumentResponse(
        String symbol,
        long version,
        InstrumentType instrumentType,
        ContractType contractType,
        String baseAsset,
        String quoteAsset,
        String settleAsset,
        long contractMultiplierPpm,
        String contractValueAsset,
        long priceTickUnits,
        long quantityStepUnits,
        long minQuantitySteps,
        long maxQuantitySteps,
        long minNotionalUnits,
        long maxNotionalUnits,
        long notionalMultiplierUnits,
        int pricePrecision,
        int quantityPrecision,
        List<String> supportedOrderTypes,
        List<String> supportedTimeInForce,
        boolean postOnlyEnabled,
        boolean reduceOnlyEnabled,
        boolean marketOrderEnabled,
        long maxLeveragePpm,
        long initialMarginRatePpm,
        long maintenanceMarginRatePpm,
        long makerFeeRatePpm,
        long takerFeeRatePpm,
        long maxPositionNotionalUnits,
        long userOpenInterestLimitRatePpm,
        long userOpenInterestLimitFloorUnits,
        int fundingIntervalHours,
        long interestRatePpm,
        long fundingRateCapPpm,
        long fundingRateFloorPpm,
        long impactNotionalUnits,
        int minValidIndexSources,
        Instant expiryTime,
        Instant deliveryTime,
        String underlyingSymbol,
        Long strikePriceUnits,
        OptionType optionType,
        OptionExerciseStyle optionExerciseStyle,
        ContractSettlementMethod settlementMethod,
        InstrumentStatus status,
        Instant effectiveTime,
        Instant createdAt,
        Instant updatedAt,
        List<RiskLimitBracket> riskLimitBrackets,
        List<IndexSourceConfig> indexSources) {
}
