BEGIN;
ALTER TABLE gateway_user_kyc_documents DROP CONSTRAINT IF EXISTS gateway_user_kyc_documents_type_check;
ALTER TABLE gateway_user_kyc_documents ADD CONSTRAINT gateway_user_kyc_documents_type_check CHECK (document_type IN ('ID_CARD','ID_CARD_FRONT','ID_CARD_BACK','ID_CARD_SELFIE','PASSPORT','ADDRESS_PROOF','BUSINESS_LICENSE','FACE_IMAGE','DRIVING_LICENSE','DRIVING_LICENSE_FRONT','DRIVING_LICENSE_BACK','RESIDENCE_PERMIT','RESIDENCE_PERMIT_FRONT','RESIDENCE_PERMIT_BACK'));
COMMIT;
