CREATE TABLE IF NOT EXISTS gateway_countries (code CHAR(2) PRIMARY KEY, flag TEXT NOT NULL, names JSONB NOT NULL, enabled BOOLEAN NOT NULL DEFAULT TRUE);

INSERT INTO gateway_countries(code,flag,names) VALUES ('AD','🇦🇩','{"en":"Andorra","zh":"安道尔"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('AE','🇦🇪','{"en":"United Arab Emirates","zh":"阿拉伯联合酋长国"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('AF','🇦🇫','{"en":"Afghanistan","zh":"阿富汗"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('AG','🇦🇬','{"en":"Antigua & Barbuda","zh":"安提瓜和巴布达"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('AI','🇦🇮','{"en":"Anguilla","zh":"安圭拉"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('AL','🇦🇱','{"en":"Albania","zh":"阿尔巴尼亚"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('AM','🇦🇲','{"en":"Armenia","zh":"亚美尼亚"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('AO','🇦🇴','{"en":"Angola","zh":"安哥拉"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('AQ','🇦🇶','{"en":"Antarctica","zh":"南极洲"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('AR','🇦🇷','{"en":"Argentina","zh":"阿根廷"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('AS','🇦🇸','{"en":"American Samoa","zh":"美属萨摩亚"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('AT','🇦🇹','{"en":"Austria","zh":"奥地利"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('AU','🇦🇺','{"en":"Australia","zh":"澳大利亚"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('AW','🇦🇼','{"en":"Aruba","zh":"阿鲁巴"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('AX','🇦🇽','{"en":"Åland Islands","zh":"奥兰群岛"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('AZ','🇦🇿','{"en":"Azerbaijan","zh":"阿塞拜疆"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('BA','🇧🇦','{"en":"Bosnia & Herzegovina","zh":"波斯尼亚和黑塞哥维那"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('BB','🇧🇧','{"en":"Barbados","zh":"巴巴多斯"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('BD','🇧🇩','{"en":"Bangladesh","zh":"孟加拉国"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('BE','🇧🇪','{"en":"Belgium","zh":"比利时"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('BF','🇧🇫','{"en":"Burkina Faso","zh":"布基纳法索"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('BG','🇧🇬','{"en":"Bulgaria","zh":"保加利亚"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('BH','🇧🇭','{"en":"Bahrain","zh":"巴林"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('BI','🇧🇮','{"en":"Burundi","zh":"布隆迪"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('BJ','🇧🇯','{"en":"Benin","zh":"贝宁"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('BL','🇧🇱','{"en":"St. Barthélemy","zh":"圣巴泰勒米"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('BM','🇧🇲','{"en":"Bermuda","zh":"百慕大"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('BN','🇧🇳','{"en":"Brunei","zh":"文莱"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('BO','🇧🇴','{"en":"Bolivia","zh":"玻利维亚"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('BQ','🇧🇶','{"en":"Caribbean Netherlands","zh":"荷属加勒比区"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('BR','🇧🇷','{"en":"Brazil","zh":"巴西"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('BS','🇧🇸','{"en":"Bahamas","zh":"巴哈马"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('BT','🇧🇹','{"en":"Bhutan","zh":"不丹"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('BV','🇧🇻','{"en":"Bouvet Island","zh":"布韦岛"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('BW','🇧🇼','{"en":"Botswana","zh":"博茨瓦纳"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('BY','🇧🇾','{"en":"Belarus","zh":"白俄罗斯"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('BZ','🇧🇿','{"en":"Belize","zh":"伯利兹"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('CA','🇨🇦','{"en":"Canada","zh":"加拿大"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('CC','🇨🇨','{"en":"Cocos (Keeling) Islands","zh":"科科斯（基林）群岛"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('CD','🇨🇩','{"en":"Congo - Kinshasa","zh":"刚果（金）"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('CF','🇨🇫','{"en":"Central African Republic","zh":"中非共和国"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('CG','🇨🇬','{"en":"Congo - Brazzaville","zh":"刚果（布）"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('CH','🇨🇭','{"en":"Switzerland","zh":"瑞士"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('CI','🇨🇮','{"en":"Côte d’Ivoire","zh":"科特迪瓦"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('CK','🇨🇰','{"en":"Cook Islands","zh":"库克群岛"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('CL','🇨🇱','{"en":"Chile","zh":"智利"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('CM','🇨🇲','{"en":"Cameroon","zh":"喀麦隆"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('CN','🇨🇳','{"en":"China","zh":"中国"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('CO','🇨🇴','{"en":"Colombia","zh":"哥伦比亚"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('CR','🇨🇷','{"en":"Costa Rica","zh":"哥斯达黎加"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('CU','🇨🇺','{"en":"Cuba","zh":"古巴"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('CV','🇨🇻','{"en":"Cape Verde","zh":"佛得角"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('CW','🇨🇼','{"en":"Curaçao","zh":"库拉索"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('CX','🇨🇽','{"en":"Christmas Island","zh":"圣诞岛"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('CY','🇨🇾','{"en":"Cyprus","zh":"塞浦路斯"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('CZ','🇨🇿','{"en":"Czechia","zh":"捷克"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('DE','🇩🇪','{"en":"Germany","zh":"德国"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('DJ','🇩🇯','{"en":"Djibouti","zh":"吉布提"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('DK','🇩🇰','{"en":"Denmark","zh":"丹麦"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('DM','🇩🇲','{"en":"Dominica","zh":"多米尼克"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('DO','🇩🇴','{"en":"Dominican Republic","zh":"多米尼加共和国"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('DZ','🇩🇿','{"en":"Algeria","zh":"阿尔及利亚"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('EC','🇪🇨','{"en":"Ecuador","zh":"厄瓜多尔"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('EE','🇪🇪','{"en":"Estonia","zh":"爱沙尼亚"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('EG','🇪🇬','{"en":"Egypt","zh":"埃及"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('EH','🇪🇭','{"en":"Western Sahara","zh":"西撒哈拉"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('ER','🇪🇷','{"en":"Eritrea","zh":"厄立特里亚"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('ES','🇪🇸','{"en":"Spain","zh":"西班牙"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('ET','🇪🇹','{"en":"Ethiopia","zh":"埃塞俄比亚"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('FI','🇫🇮','{"en":"Finland","zh":"芬兰"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('FJ','🇫🇯','{"en":"Fiji","zh":"斐济"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('FK','🇫🇰','{"en":"Falkland Islands","zh":"福克兰群岛"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('FM','🇫🇲','{"en":"Micronesia","zh":"密克罗尼西亚"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('FO','🇫🇴','{"en":"Faroe Islands","zh":"法罗群岛"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('FR','🇫🇷','{"en":"France","zh":"法国"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('GA','🇬🇦','{"en":"Gabon","zh":"加蓬"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('GB','🇬🇧','{"en":"United Kingdom","zh":"英国"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('GD','🇬🇩','{"en":"Grenada","zh":"格林纳达"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('GE','🇬🇪','{"en":"Georgia","zh":"格鲁吉亚"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('GF','🇬🇫','{"en":"French Guiana","zh":"法属圭亚那"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('GG','🇬🇬','{"en":"Guernsey","zh":"根西岛"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('GH','🇬🇭','{"en":"Ghana","zh":"加纳"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('GI','🇬🇮','{"en":"Gibraltar","zh":"直布罗陀"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('GL','🇬🇱','{"en":"Greenland","zh":"格陵兰"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('GM','🇬🇲','{"en":"Gambia","zh":"冈比亚"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('GN','🇬🇳','{"en":"Guinea","zh":"几内亚"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('GP','🇬🇵','{"en":"Guadeloupe","zh":"瓜德罗普"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('GQ','🇬🇶','{"en":"Equatorial Guinea","zh":"赤道几内亚"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('GR','🇬🇷','{"en":"Greece","zh":"希腊"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('GS','🇬🇸','{"en":"South Georgia & South Sandwich Islands","zh":"南乔治亚和南桑威奇群岛"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('GT','🇬🇹','{"en":"Guatemala","zh":"危地马拉"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('GU','🇬🇺','{"en":"Guam","zh":"关岛"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('GW','🇬🇼','{"en":"Guinea-Bissau","zh":"几内亚比绍"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('GY','🇬🇾','{"en":"Guyana","zh":"圭亚那"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('HK','🇭🇰','{"en":"Hong Kong SAR China","zh":"中国香港特别行政区"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('HM','🇭🇲','{"en":"Heard & McDonald Islands","zh":"赫德岛和麦克唐纳群岛"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('HN','🇭🇳','{"en":"Honduras","zh":"洪都拉斯"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('HR','🇭🇷','{"en":"Croatia","zh":"克罗地亚"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('HT','🇭🇹','{"en":"Haiti","zh":"海地"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('HU','🇭🇺','{"en":"Hungary","zh":"匈牙利"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('ID','🇮🇩','{"en":"Indonesia","zh":"印度尼西亚"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('IE','🇮🇪','{"en":"Ireland","zh":"爱尔兰"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('IL','🇮🇱','{"en":"Israel","zh":"以色列"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('IM','🇮🇲','{"en":"Isle of Man","zh":"马恩岛"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('IN','🇮🇳','{"en":"India","zh":"印度"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('IO','🇮🇴','{"en":"British Indian Ocean Territory","zh":"英属印度洋领地"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('IQ','🇮🇶','{"en":"Iraq","zh":"伊拉克"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('IR','🇮🇷','{"en":"Iran","zh":"伊朗"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('IS','🇮🇸','{"en":"Iceland","zh":"冰岛"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('IT','🇮🇹','{"en":"Italy","zh":"意大利"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('JE','🇯🇪','{"en":"Jersey","zh":"泽西岛"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('JM','🇯🇲','{"en":"Jamaica","zh":"牙买加"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('JO','🇯🇴','{"en":"Jordan","zh":"约旦"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('JP','🇯🇵','{"en":"Japan","zh":"日本"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('KE','🇰🇪','{"en":"Kenya","zh":"肯尼亚"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('KG','🇰🇬','{"en":"Kyrgyzstan","zh":"吉尔吉斯斯坦"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('KH','🇰🇭','{"en":"Cambodia","zh":"柬埔寨"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('KI','🇰🇮','{"en":"Kiribati","zh":"基里巴斯"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('KM','🇰🇲','{"en":"Comoros","zh":"科摩罗"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('KN','🇰🇳','{"en":"St. Kitts & Nevis","zh":"圣基茨和尼维斯"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('KP','🇰🇵','{"en":"North Korea","zh":"朝鲜"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('KR','🇰🇷','{"en":"South Korea","zh":"韩国"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('KW','🇰🇼','{"en":"Kuwait","zh":"科威特"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('KY','🇰🇾','{"en":"Cayman Islands","zh":"开曼群岛"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('KZ','🇰🇿','{"en":"Kazakhstan","zh":"哈萨克斯坦"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('LA','🇱🇦','{"en":"Laos","zh":"老挝"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('LB','🇱🇧','{"en":"Lebanon","zh":"黎巴嫩"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('LC','🇱🇨','{"en":"St. Lucia","zh":"圣卢西亚"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('LI','🇱🇮','{"en":"Liechtenstein","zh":"列支敦士登"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('LK','🇱🇰','{"en":"Sri Lanka","zh":"斯里兰卡"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('LR','🇱🇷','{"en":"Liberia","zh":"利比里亚"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('LS','🇱🇸','{"en":"Lesotho","zh":"莱索托"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('LT','🇱🇹','{"en":"Lithuania","zh":"立陶宛"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('LU','🇱🇺','{"en":"Luxembourg","zh":"卢森堡"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('LV','🇱🇻','{"en":"Latvia","zh":"拉脱维亚"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('LY','🇱🇾','{"en":"Libya","zh":"利比亚"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('MA','🇲🇦','{"en":"Morocco","zh":"摩洛哥"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('MC','🇲🇨','{"en":"Monaco","zh":"摩纳哥"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('MD','🇲🇩','{"en":"Moldova","zh":"摩尔多瓦"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('ME','🇲🇪','{"en":"Montenegro","zh":"黑山"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('MF','🇲🇫','{"en":"St. Martin","zh":"法属圣马丁"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('MG','🇲🇬','{"en":"Madagascar","zh":"马达加斯加"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('MH','🇲🇭','{"en":"Marshall Islands","zh":"马绍尔群岛"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('MK','🇲🇰','{"en":"North Macedonia","zh":"北马其顿"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('ML','🇲🇱','{"en":"Mali","zh":"马里"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('MM','🇲🇲','{"en":"Myanmar (Burma)","zh":"缅甸"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('MN','🇲🇳','{"en":"Mongolia","zh":"蒙古"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('MO','🇲🇴','{"en":"Macao SAR China","zh":"中国澳门特别行政区"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('MP','🇲🇵','{"en":"Northern Mariana Islands","zh":"北马里亚纳群岛"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('MQ','🇲🇶','{"en":"Martinique","zh":"马提尼克"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('MR','🇲🇷','{"en":"Mauritania","zh":"毛里塔尼亚"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('MS','🇲🇸','{"en":"Montserrat","zh":"蒙特塞拉特"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('MT','🇲🇹','{"en":"Malta","zh":"马耳他"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('MU','🇲🇺','{"en":"Mauritius","zh":"毛里求斯"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('MV','🇲🇻','{"en":"Maldives","zh":"马尔代夫"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('MW','🇲🇼','{"en":"Malawi","zh":"马拉维"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('MX','🇲🇽','{"en":"Mexico","zh":"墨西哥"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('MY','🇲🇾','{"en":"Malaysia","zh":"马来西亚"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('MZ','🇲🇿','{"en":"Mozambique","zh":"莫桑比克"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('NA','🇳🇦','{"en":"Namibia","zh":"纳米比亚"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('NC','🇳🇨','{"en":"New Caledonia","zh":"新喀里多尼亚"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('NE','🇳🇪','{"en":"Niger","zh":"尼日尔"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('NF','🇳🇫','{"en":"Norfolk Island","zh":"诺福克岛"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('NG','🇳🇬','{"en":"Nigeria","zh":"尼日利亚"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('NI','🇳🇮','{"en":"Nicaragua","zh":"尼加拉瓜"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('NL','🇳🇱','{"en":"Netherlands","zh":"荷兰"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('NO','🇳🇴','{"en":"Norway","zh":"挪威"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('NP','🇳🇵','{"en":"Nepal","zh":"尼泊尔"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('NR','🇳🇷','{"en":"Nauru","zh":"瑙鲁"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('NU','🇳🇺','{"en":"Niue","zh":"纽埃"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('NZ','🇳🇿','{"en":"New Zealand","zh":"新西兰"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('OM','🇴🇲','{"en":"Oman","zh":"阿曼"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('PA','🇵🇦','{"en":"Panama","zh":"巴拿马"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('PE','🇵🇪','{"en":"Peru","zh":"秘鲁"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('PF','🇵🇫','{"en":"French Polynesia","zh":"法属波利尼西亚"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('PG','🇵🇬','{"en":"Papua New Guinea","zh":"巴布亚新几内亚"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('PH','🇵🇭','{"en":"Philippines","zh":"菲律宾"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('PK','🇵🇰','{"en":"Pakistan","zh":"巴基斯坦"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('PL','🇵🇱','{"en":"Poland","zh":"波兰"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('PM','🇵🇲','{"en":"St. Pierre & Miquelon","zh":"圣皮埃尔和密克隆群岛"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('PN','🇵🇳','{"en":"Pitcairn Islands","zh":"皮特凯恩群岛"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('PR','🇵🇷','{"en":"Puerto Rico","zh":"波多黎各"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('PS','🇵🇸','{"en":"Palestinian Territories","zh":"巴勒斯坦领土"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('PT','🇵🇹','{"en":"Portugal","zh":"葡萄牙"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('PW','🇵🇼','{"en":"Palau","zh":"帕劳"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('PY','🇵🇾','{"en":"Paraguay","zh":"巴拉圭"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('QA','🇶🇦','{"en":"Qatar","zh":"卡塔尔"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('RE','🇷🇪','{"en":"Réunion","zh":"留尼汪"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('RO','🇷🇴','{"en":"Romania","zh":"罗马尼亚"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('RS','🇷🇸','{"en":"Serbia","zh":"塞尔维亚"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('RU','🇷🇺','{"en":"Russia","zh":"俄罗斯"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('RW','🇷🇼','{"en":"Rwanda","zh":"卢旺达"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('SA','🇸🇦','{"en":"Saudi Arabia","zh":"沙特阿拉伯"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('SB','🇸🇧','{"en":"Solomon Islands","zh":"所罗门群岛"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('SC','🇸🇨','{"en":"Seychelles","zh":"塞舌尔"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('SD','🇸🇩','{"en":"Sudan","zh":"苏丹"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('SE','🇸🇪','{"en":"Sweden","zh":"瑞典"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('SG','🇸🇬','{"en":"Singapore","zh":"新加坡"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('SH','🇸🇭','{"en":"St. Helena","zh":"圣赫勒拿"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('SI','🇸🇮','{"en":"Slovenia","zh":"斯洛文尼亚"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('SJ','🇸🇯','{"en":"Svalbard & Jan Mayen","zh":"斯瓦尔巴和扬马延"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('SK','🇸🇰','{"en":"Slovakia","zh":"斯洛伐克"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('SL','🇸🇱','{"en":"Sierra Leone","zh":"塞拉利昂"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('SM','🇸🇲','{"en":"San Marino","zh":"圣马力诺"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('SN','🇸🇳','{"en":"Senegal","zh":"塞内加尔"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('SO','🇸🇴','{"en":"Somalia","zh":"索马里"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('SR','🇸🇷','{"en":"Suriname","zh":"苏里南"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('SS','🇸🇸','{"en":"South Sudan","zh":"南苏丹"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('ST','🇸🇹','{"en":"São Tomé & Príncipe","zh":"圣多美和普林西比"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('SV','🇸🇻','{"en":"El Salvador","zh":"萨尔瓦多"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('SX','🇸🇽','{"en":"Sint Maarten","zh":"荷属圣马丁"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('SY','🇸🇾','{"en":"Syria","zh":"叙利亚"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('SZ','🇸🇿','{"en":"Eswatini","zh":"斯威士兰"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('TC','🇹🇨','{"en":"Turks & Caicos Islands","zh":"特克斯和凯科斯群岛"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('TD','🇹🇩','{"en":"Chad","zh":"乍得"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('TF','🇹🇫','{"en":"French Southern Territories","zh":"法属南部领地"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('TG','🇹🇬','{"en":"Togo","zh":"多哥"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('TH','🇹🇭','{"en":"Thailand","zh":"泰国"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('TJ','🇹🇯','{"en":"Tajikistan","zh":"塔吉克斯坦"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('TK','🇹🇰','{"en":"Tokelau","zh":"托克劳"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('TL','🇹🇱','{"en":"Timor-Leste","zh":"东帝汶"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('TM','🇹🇲','{"en":"Turkmenistan","zh":"土库曼斯坦"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('TN','🇹🇳','{"en":"Tunisia","zh":"突尼斯"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('TO','🇹🇴','{"en":"Tonga","zh":"汤加"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('TR','🇹🇷','{"en":"Türkiye","zh":"土耳其"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('TT','🇹🇹','{"en":"Trinidad & Tobago","zh":"特立尼达和多巴哥"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('TV','🇹🇻','{"en":"Tuvalu","zh":"图瓦卢"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('TW','🇹🇼','{"en":"Taiwan","zh":"台湾"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('TZ','🇹🇿','{"en":"Tanzania","zh":"坦桑尼亚"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('UA','🇺🇦','{"en":"Ukraine","zh":"乌克兰"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('UG','🇺🇬','{"en":"Uganda","zh":"乌干达"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('UM','🇺🇲','{"en":"U.S. Outlying Islands","zh":"美国本土外小岛屿"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('US','🇺🇸','{"en":"United States","zh":"美国"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('UY','🇺🇾','{"en":"Uruguay","zh":"乌拉圭"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('UZ','🇺🇿','{"en":"Uzbekistan","zh":"乌兹别克斯坦"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('VA','🇻🇦','{"en":"Vatican City","zh":"梵蒂冈"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('VC','🇻🇨','{"en":"St. Vincent & Grenadines","zh":"圣文森特和格林纳丁斯"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('VE','🇻🇪','{"en":"Venezuela","zh":"委内瑞拉"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('VG','🇻🇬','{"en":"British Virgin Islands","zh":"英属维尔京群岛"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('VI','🇻🇮','{"en":"U.S. Virgin Islands","zh":"美属维尔京群岛"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('VN','🇻🇳','{"en":"Vietnam","zh":"越南"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('VU','🇻🇺','{"en":"Vanuatu","zh":"瓦努阿图"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('WF','🇼🇫','{"en":"Wallis & Futuna","zh":"瓦利斯和富图纳"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('WS','🇼🇸','{"en":"Samoa","zh":"萨摩亚"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('YE','🇾🇪','{"en":"Yemen","zh":"也门"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('YT','🇾🇹','{"en":"Mayotte","zh":"马约特"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('ZA','🇿🇦','{"en":"South Africa","zh":"南非"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('ZM','🇿🇲','{"en":"Zambia","zh":"赞比亚"}'::jsonb) ON CONFLICT (code) DO NOTHING;
INSERT INTO gateway_countries(code,flag,names) VALUES ('ZW','🇿🇼','{"en":"Zimbabwe","zh":"津巴布韦"}'::jsonb) ON CONFLICT (code) DO NOTHING;

ALTER TABLE gateway_user_kyc_documents DROP CONSTRAINT IF EXISTS gateway_user_kyc_documents_type_check;
ALTER TABLE gateway_user_kyc_documents ADD CONSTRAINT gateway_user_kyc_documents_type_check CHECK (
 document_type IN ('ID_CARD','ID_CARD_FRONT','ID_CARD_BACK','ID_CARD_SELFIE','PASSPORT','ADDRESS_PROOF','BUSINESS_LICENSE','FACE_IMAGE')
);
