package com.surprising.account.api.model;

public enum AccountUserCommandType {
    ORDER_RESERVE,
    ORDER_RELEASE,
    TRADE_SIDE_SETTLE,
    FUNDING_SETTLE,
    ADL_DEFICIT_RESERVE,
    ADL_TARGET_SETTLE,
    ADL_DEFICIT_FINALIZE,
    ADL_DEFICIT_RELEASE,
    INSURANCE_DEFICIT_RESERVE,
    INSURANCE_DEFICIT_FINALIZE,
    INSURANCE_DEFICIT_RELEASE,
    BALANCE_ADJUST,
    PRODUCT_BALANCE_ADJUST,
    PRODUCT_TRANSFER,
    POSITION_MARGIN_ADJUST,
    POSITION_MODE_UPDATE,
    DELIVERY_SETTLE,
    OPTION_EXERCISE
}
