CREATE SEQUENCE IF NOT EXISTS risk_snapshot_id_seq AS BIGINT START WITH 1;
CREATE SEQUENCE IF NOT EXISTS risk_event_id_seq AS BIGINT START WITH 1;
CREATE SEQUENCE IF NOT EXISTS risk_liquidation_candidate_id_seq AS BIGINT START WITH 1;
CREATE SEQUENCE IF NOT EXISTS risk_outbox_id_seq AS BIGINT START WITH 1;
