CREATE TABLE IF NOT EXISTS core_funding_settlement_projection (
    product_line VARCHAR(32) NOT NULL,
    settlement_id BIGINT NOT NULL,
    export_sequence BIGINT NOT NULL,
    symbol VARCHAR(64) NOT NULL,
    instrument_version BIGINT NOT NULL,
    funding_rate_ppm BIGINT NOT NULL,
    command_status VARCHAR(32) NOT NULL,
    result_code VARCHAR(64) NOT NULL,
    total_long_payment_units BIGINT NOT NULL,
    total_short_payment_units BIGINT NOT NULL,
    position_count INTEGER NOT NULL,
    occurred_at_epoch_ms BIGINT NOT NULL,
    PRIMARY KEY (product_line, symbol, settlement_id),
    UNIQUE (product_line, export_sequence)
);

CREATE INDEX IF NOT EXISTS idx_core_funding_settlement_symbol
    ON core_funding_settlement_projection (product_line, symbol, settlement_id DESC);

CREATE TABLE IF NOT EXISTS core_funding_payment_projection (
    payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_line VARCHAR(32) NOT NULL,
    export_sequence BIGINT NOT NULL,
    payment_index INTEGER NOT NULL,
    settlement_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    symbol VARCHAR(64) NOT NULL,
    margin_mode VARCHAR(16) NOT NULL,
    position_side VARCHAR(16) NOT NULL,
    asset VARCHAR(20) NOT NULL,
    signed_quantity_steps BIGINT NOT NULL,
    notional_units BIGINT NOT NULL,
    funding_rate_ppm BIGINT NOT NULL,
    amount_units BIGINT NOT NULL,
    occurred_at_epoch_ms BIGINT NOT NULL,
    UNIQUE (product_line, export_sequence, payment_index)
);

CREATE INDEX IF NOT EXISTS idx_core_funding_payment_user
    ON core_funding_payment_projection (product_line, user_id, payment_id DESC);

CREATE INDEX IF NOT EXISTS idx_core_funding_payment_user_symbol
    ON core_funding_payment_projection (product_line, user_id, symbol, payment_id DESC);
